<?php

namespace DoctrineORMModule\Proxy\__CG__\Games\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Players extends \Games\Entity\Players implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setMark($mark)
    {
        $this->__load();
        return parent::setMark($mark);
    }

    public function getMark()
    {
        $this->__load();
        return parent::getMark();
    }

    public function hasPendingGame()
    {
        $this->__load();
        return parent::hasPendingGame();
    }

    public function getGame()
    {
        $this->__load();
        return parent::getGame();
    }

    public function setGame($game)
    {
        $this->__load();
        return parent::setGame($game);
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setOutcome($outcome)
    {
        $this->__load();
        return parent::setOutcome($outcome);
    }

    public function getOutcome()
    {
        $this->__load();
        return parent::getOutcome();
    }

    public function setTimeJoined($time_joined)
    {
        $this->__load();
        return parent::setTimeJoined($time_joined);
    }

    public function getTimeJoined()
    {
        $this->__load();
        return parent::getTimeJoined();
    }

    public function setTurnold($turn)
    {
        $this->__load();
        return parent::setTurnold($turn);
    }

    public function setTurn($turn_strategy)
    {
        $this->__load();
        return parent::setTurn($turn_strategy);
    }

    public function getTurn()
    {
        $this->__load();
        return parent::getTurn();
    }

    public function setUser($user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'turn', 'time_joined', 'outcome', 'mark', 'game', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}