<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
    jQuery(function($) {
    dataString = 'testing';
    $('#trigger').click(function(){
        $.ajax({
            url: '/testing/getdata',
            type: 'POST',
            dataType: "json",
            data:{data: dataString},
            success: function(response){
                console.log(response);
            }
        });
    });
    });

</script>
<?php
echo $message;
?>

<p id='trigger'>Trigger</p>